# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          xcodebuild build-for-testing \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -CODE_SIGNING_ALLOWED=NO;
        env:
          PROJECT: Record Player.xcodeproj
          SCHEME: Record Player

      - name: Install Dependencies
        run: |
          brew install create-dmg
          
      - name: Build Unsigned Release
        run: |
          xcodebuild build \
            -CODE_SIGNING_ALLOWED=NO \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -derivedDataPath DerivedData \
            -configuration Release;
        env:
          PROJECT: Record Player.xcodeproj
          SCHEME: Record Player

      - name: Build DMG
        run: | 
          export APP_PATH="$(pwd)/DerivedData/Build/Products/Release/Record Player.app"
          create-dmg \
          --no-internet-enable \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --app-drop-link 600 185 \
          Radio\ Record.dmg $(pwd)/DerivedData/Build/Products/Release/Record\ Player.app;
        
