# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          xcodebuild build-for-testing \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -CODE_SIGNING_ALLOWED=NO;
        env:
          PROJECT: Record Player.xcodeproj
          SCHEME: Record Player
          
      - uses: actions/checkout@v4
      - name: Build Unsigned Release
        run: |
          xcodebuild build \
            -CODE_SIGNING_ALLOWED=NO;

      - name: Install Dependencies
        run: |
          brew install create-dmg
        
      - uses: actions/checkout@v4
      - name: Build DMG
        run: | 
          ls && \
          create-dmg \
          build/Radio\ Record.dmg \ 
          $(pwd)/build/Release/Record\ Player.app;
        
