# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Run Tests
        run: |
          xcodebuild build-for-testing \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -CODE_SIGNING_ALLOWED=NO;
        env:
          PROJECT: Record Player.xcodeproj
          SCHEME: Record Player
      - name: Build Unsigned Release
        run: |
          xcodebuild build \
            -CODE_SIGNING_ALLOWED=NO;
      - name: Build DMG
        run: | 
          create-dmg \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "Radio Record.app" 200 190 \
          --hide-extension "Radio Record.app" \
          --app-drop-link 600 185 \
          build/Radio\ Record.dmg \ 
          build/Release/Record\ Player.app;
        
