name: Build

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          xcodebuild build-for-testing \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -CODE_SIGNING_ALLOWED=NO;
        env:
          PROJECT: Record Player.xcodeproj
          SCHEME: Record Player

      - name: Install Dependencies
        run: |
          brew install create-dmg
          
      - name: Build Unsigned Release
        run: |
          xcodebuild build \
            -CODE_SIGNING_ALLOWED=NO \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -derivedDataPath DerivedData \
            -configuration Release;
        env:
          PROJECT: Record Player.xcodeproj
          SCHEME: Record Player

      - name: Build DMG
        run: | 
          export APP_PATH="$(pwd)/DerivedData/Build/Products/Release/Record Player.app"
          create-dmg \
          --no-internet-enable \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --app-drop-link 600 185 \
          "Radio Record_1.0.1.dmg" $(pwd)/DerivedData/Build/Products/Release/Record\ Player.app;
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "Radio Record"
          path: Radio Record_1.0.1.dmg
         
  release:
    needs: build
    runs-on: macOS-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: Radio Record
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: 1.0.1
        files: Radio Record_1.0.1.dmg
        
